EMPTY = -1
AVAILABLE = 0
WHITE_DISK = 1
BLACK_DISK = 2

DEPTH_EASY = 1
DEPTH_MEDIUM = 3
DEPTH_HARD = 5

DIFF_EASY = "easy"
DIFF_MEDIUM = "medium"
DIFF_HARD = "hard"

STATE_NORMAL = "normal"
STATE_WHITE_WON = "white"
STATE_BLACK_WON = "black"
STATE_DRAW = "draw"
STATE_PLAYER_TURN = "player"
STATE_AI_TURN = "computer"

MAX = 1000
MIN = -1000
